---
# Application paths
praat: /usr/bin/praat
ffmpeg: /usr/bin/ffmpeg
# Praat script paths
analysis: praatscripts/analysis.praat
extraction: praatscripts/extraction.praat
synthesis: praatscripts/synthesis.praat
